# ======================
# Clash-Fallback æ¨¡å¼é…ç½®
# ======================

# ==============
# æœºåœºè®¢é˜…èŠ‚ç‚¹è®¾ç½®
# ==============
proxy-providers:
  ALLinOne:
    url: "https://XXX.XXX.XXX"
    type: http
    interval: 86400
    health-check:
      enable: true
      url: https://www.gstatic.com/generate_204
      interval: 300
    proxy: ç›´è¿  

proxies:
  - {name: ç›´è¿, type: direct}
  - {name: æ‹’ç», type: reject}

# ==================================================
# ä¸»è¦ç«¯å£è®¾ç½®ï¼Œè¯¥è®¾ç½®åœ¨OpenClashè¦†å†™è®¾ç½®-å¸¸è§„è®¾ç½®ä¸­ä½“ç°
# ==================================================
port: 7890
socks-port: 7891
redir-port: 7892
mixed-port: 7893
tproxy-port: 7895

allow-lan: true
mode: rule
log-level: info

# =========================================================================================================
# OpenClashç®¡ç†é¢æ¿è®¾ç½®ï¼Œè¯¥è®¾ç½®åœ¨OpenClashæ’ä»¶è®¾ç½®-å¤–éƒ¨æ§åˆ¶ä¸­è®¾ç½®ï¼Œå¯ä»¥ä¸åœ¨æœ¬é…ç½®æ–‡ä»¶ä¸­è®¾ç½®ï¼Œå»ºè®®ä½¿ç”¨Zashboardé¢æ¿
# =========================================================================================================

#external-controller: 0.0.0.0:9090
#external-ui: ui
#external-ui-name: zashboard
#external-ui-url: https://gh-proxy.com/github.com/Zephyruso/zashboard/archive/refs/heads/gh-pages.zip
#secret: "123456"

# ==========================================================================
# DNSè®¾ç½®ï¼Œè¯¥è®¾ç½®åœ¨OpenClashè¦†å†™è®¾ç½®-å¸¸è§„è®¾ç½®/DNSè®¾ç½®ä¸­è®¾ç½®
# fake-ip-filterä¸­å»ºè®®æ·»åŠ èŠ‚ç‚¹è®¢é˜…ä¸å„èŠ‚ç‚¹ä½¿ç”¨çš„é¡¶çº§åŸŸåå¹¶åœ¨è§„åˆ™è®¾ç½®ä¸­æ·»åŠ ç›´è¿è§„åˆ™
# ipv6æ ¹æ®è‡ªèº«ç½‘ç»œæƒ…å†µé€‰æ‹©æ˜¯å¦å¯ç”¨ï¼Œå¦‚å¯ç”¨ï¼Œéœ€è¦åœ¨OpenClashæ’ä»¶è®¾ç½®-IPv6åŒæ—¶è®¾ç½®
# ==========================================================================
dns:
  enable: true
  listen: 0.0.0.0:7874
  ipv6: false
  enhanced-mode: fake-ip
  fake-ip-range: 198.20.0.1/16
# ======================================================================================================================
# ä»¥ä¸‹é…ç½®ä¿®æ”¹OpenClashä¸­è¦†å†™è®¾ç½®ä¸­NameServer|FallBack|Default-NameServerçš„è®¾ç½®ï¼ŒDNS nameserverä¿®æ”¹ä¸ºè¿è¥å•†DNSï¼Œå–æ¶ˆå…¶ä»–å‹¾é€‰ï¼›
# ======================================================================================================================
  nameserver:
    - 211.136.150.66
    - 211.136.112.50
  fake-ip-filter-mode: blacklist
  fake-ip-filter:
    - +.lan
    - +.local
    - geosite:cn
# VPN Domain & My Domain
    - +.kuaileiruko.top
    - +.aiwowo.xyz
    - +.moe233.org
    - +.qchwnd.moe
    - +.snoweer.cn
    - +.snoweer.cloud
    - +.bigme.pro
    - +.moe233.app
    - +.cnct.xn--fiqs8s
    - +.cnct.ä¸­å›½
# å¿«çŒ«
    - +.km688.ink
# ç«çƒ§ 
    - +.onesubv.site
    - +.oneyyds.online
    - +.fengyyds.site
    - +.onemg.top    
# çŒ«è€³ 
    - +.chybinc.com
# BestVPN 
    - +.invitevp.com
    - +.vp2.us
# å°ç‰›
    - +.xiaoniuyun.cc  
# ç¡…è°·
    - +.apple-bing.sbs  
# æ— ç•Œ
    - +.bncrcloud.com
# å†°äº‘
    - +.xby01.xyz
# ç‰›é€¼   
    - +.idsduf.com  
    - +.66jc.top
# æé€Ÿé€š        
    - +.gfw.gg
# èŒç‹—       
    - +.moedog.cloud
# å…¶ä»–     
    - +.ynhtbank.com
    - +.qeayr.cn
    - +.saojc.xyz   
    - +.sssyun.xyz
    - +.dler.cloud
    - +.0tk8a3a1q4t94dler.com    
    - +.aerianas.top
    - +.gptacg.top
    - +.wxda.net

# ======================================================================================
# TUNæ¨¡å—ï¼Œè¯¥è®¾ç½®åœ¨OpenClashæ’ä»¶è®¾ç½®-æ¨¡å¼è®¾ç½®ä¸­é€‰æ‹©ï¼Œå¯ä»¥ä¸åœ¨æœ¬é…ç½®æ–‡ä»¶ä¸­è®¾ç½®ï¼Œå»ºè®®ä½¿ç”¨å¢å¼ºæ¨¡å¼
# ======================================================================================
#tun:
#  enable: true
#  stack: gvisor
#  device: utun
#  endpoint-independent-nat: true
#  auto-route: false
#  auto-detect-interface: false
#  auto-redirect: false
#  strict-route: false

# =======================================================
# fake-ipæŒä¹…åŒ–è®¾ç½®ï¼Œè¯¥è®¾ç½®åœ¨OpenClashè¦†å†™è®¾ç½®-DNSè®¾ç½®ä¸­è®¾ç½®
# =======================================================
profile:
  store-selected: true
  store-fake-ip: true

# ========================
# ç­–ç•¥ç»„ã€åˆ†æµè§„åˆ™åŠæ–¹æ³•å®šä¹‰
# ========================
default: &default
  type: select
  proxies:
    - ç›´è¿
    - æ‰€æœ‰-æ‰‹åŠ¨
    - æ‰€æœ‰-è‡ªåŠ¨
    - é¦™æ¸¯-æ•…è½¬
    - å°æ¹¾-æ•…è½¬
    - æ—¥æœ¬-æ•…è½¬
    - æ–°åŠ å¡-æ•…è½¬
    - éŸ©å›½-æ•…è½¬
    - ç¾å›½-æ•…è½¬
    - è‹±å›½-æ•…è½¬
    - å…¶ä»–-æ•…è½¬
    - æ‹’ç»

proxy-groups:
  # ä¸šåŠ¡åˆ†æµç»„
  - {name: AI-T, <<: *default}
  - {name: AI-A, <<: *default}
  - {name: AI-S, <<: *default}
  - {name: AI-H, <<: *default}
  - {name: Google, <<: *default}
  - {name: GitHub, <<: *default}
  - {name: YouTube, <<: *default}
  - {name: Microsoft, <<: *default}
  - {name: Apple, <<: *default}
  - {name: Amazon, <<: *default}
  - {name: Social, <<: *default}
  - {name: Steam, <<: *default}
  - {name: Game, <<: *default}
  - {name: Stream, <<: *default}
  - {name: Crypto, <<: *default}
  - {name: Test, <<: *default}
  - {name: Block, <<: *default}
  - {name: Global, <<: *default}
  - {name: Mainland, <<: *default}
  - {name: Others, <<: *default}

  - name: æ‰€æœ‰-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  - name: æ‰€æœ‰-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»)).)*$"

  # é¦™æ¸¯ç»„
  - name: é¦™æ¸¯-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - é¦™æ¸¯-æ‰‹åŠ¨
      - é¦™æ¸¯-è‡ªåŠ¨
  
  - name: é¦™æ¸¯-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
    
  - name: é¦™æ¸¯-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong)).*$"
 
  # å°æ¹¾ç»„
  - name: å°æ¹¾-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - å°æ¹¾-æ‰‹åŠ¨
      - å°æ¹¾-è‡ªåŠ¨
  - name: å°æ¹¾-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"
  - name: å°æ¹¾-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan)).*$"

  # æ—¥æœ¬ç»„
  - name: æ—¥æœ¬-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - æ—¥æœ¬-æ‰‹åŠ¨
      - æ—¥æœ¬-è‡ªåŠ¨
  - name: æ—¥æœ¬-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"
  - name: æ—¥æœ¬-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan)).*$"

  # æ–°åŠ å¡ç»„
  - name: æ–°åŠ å¡-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - æ–°åŠ å¡-æ‰‹åŠ¨
      - æ–°åŠ å¡-è‡ªåŠ¨
  - name: æ–°åŠ å¡-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"
  - name: æ–°åŠ å¡-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore)).*$"

  # éŸ©å›½ç»„
  - name: éŸ©å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - éŸ©å›½-æ‰‹åŠ¨
      - éŸ©å›½-è‡ªåŠ¨
  - name: éŸ©å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"
  - name: éŸ©å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea)).*$"

  # ç¾å›½ç»„
  - name: ç¾å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - ç¾å›½-æ‰‹åŠ¨
      - ç¾å›½-è‡ªåŠ¨
  - name: ç¾å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"
  - name: ç¾å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States)).*$"

  # è‹±å›½ç»„
  - name: è‹±å›½-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - è‹±å›½-æ‰‹åŠ¨
      - è‹±å›½-è‡ªåŠ¨
  - name: è‹±å›½-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"
  - name: è‹±å›½-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "(?=.*(è‹±å›½|è‹±|ä¼¦æ•¦|UK|United Kingdom|ğŸ‡¬ğŸ‡§|London)).*$"

  # å…¶ä»–ç»„
  - name: å…¶ä»–-æ•…è½¬
    type: fallback
    interval: 300
    lazy: false
    proxies:
      - å…¶ä»–-æ‰‹åŠ¨
      - å…¶ä»–-è‡ªåŠ¨
  - name: å…¶ä»–-æ‰‹åŠ¨
    type: select
    include-all: true
    filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"
  - name: å…¶ä»–-è‡ªåŠ¨
    type: url-test
    include-all: true
    tolerance: 50
    interval: 300
    filter: "^((?!(ç›´è¿|æ‹’ç»|å¹¿æ¸¯|é¦™æ¸¯|HK|Hong Kong|ğŸ‡­ğŸ‡°|HongKong|å¹¿å°|å°æ¹¾|å°ç£|TW|Tai Wan|ğŸ‡¹ğŸ‡¼|ğŸ‡¨ğŸ‡³|TaiWan|Taiwan|å¹¿æ—¥|æ—¥æœ¬|JP|å·æ—¥|ä¸œäº¬|å¤§é˜ª|æ³‰æ—¥|åŸ¼ç‰|æ²ªæ—¥|æ·±æ—¥|ğŸ‡¯ğŸ‡µ|Japan|å¹¿æ–°|æ–°åŠ å¡|SG|å¡|ç‹®åŸ|ğŸ‡¸ğŸ‡¬|Singapore|å¹¿éŸ©|éŸ©å›½|éŸ“åœ‹|KR|é¦–å°”|æ˜¥å·|ğŸ‡°ğŸ‡·|Korea|å¹¿ç¾|US|ç¾å›½|çº½çº¦|æ³¢ç‰¹å…°|è¾¾æ‹‰æ–¯|ä¿„å‹’|å‡¤å‡°åŸ|è´¹åˆ©è’™|æ´›æ‰|åœ£ä½•å¡|åœ£å…‹æ‹‰|è¥¿é›…|èŠåŠ |ğŸ‡ºğŸ‡¸|United States|è‹±å›½|UK|United Kingdom|ä¼¦æ•¦|è‹±|London|ğŸ‡¬ğŸ‡§)).)*$"

# ===============
# è§„åˆ™å¼•æ“ï¼ˆrulesï¼‰
# ===============
rules:
  - RULE-SET,Claude / Domain,AI-A
  - RULE-SET,ChatGPT / Domain,AI-T
  - RULE-SET,Copilot / Domain,AI-T
  - RULE-SET,Gemini / Domain,AI-T
  - RULE-SET,AI / Domain,AI-H
  - RULE-SET,Perplexity / Domain,AI-H
  - RULE-SET,Meta AI / Domain,AI-S
  - RULE-SET,Google / Domain,Google
  - RULE-SET,Google / IP,Google,no-resolve
  - RULE-SET,GitHub / Domain,GitHub
  - RULE-SET,Youtube / Domain,YouTube
  - RULE-SET,Microsoft / Domain,Microsoft
  - RULE-SET,Apple / Domain,Apple
  - RULE-SET,Apple-CN / Domain,Apple
  - RULE-SET,Amazon / Domain,Amazon
  - RULE-SET,TikTok / Domain,Social
  - RULE-SET,Telegram / Domain,Social
  - RULE-SET,Telegram / IP,Social,no-resolve
  - RULE-SET,Twitter / Domain,Social
  - RULE-SET,WhatsApp / Domain,Social
  - RULE-SET,Facebook / Domain,Social
  - RULE-SET,Steam / Domain,Steam
  - RULE-SET,Epic / Domain,Game
  - RULE-SET,EA / Domain,Game
  - RULE-SET,Blizzard / Domain,Game
  - RULE-SET,UBI / Domain,Game
  - RULE-SET,PlayStation / Domain,Game
  - RULE-SET,Nintend / Domain,Game
  - RULE-SET,Netflix / Domain,Stream
  - RULE-SET,Netflix / IP,Stream,no-resolve
  - RULE-SET,Disney / Domain,Stream
  - RULE-SET,HBO / Domain,Stream
  - RULE-SET,Spotify / Domain,Stream
  - RULE-SET,OKX / Domain,Crypto
  - RULE-SET,Bybit / Domain,Crypto
  - RULE-SET,Binance / Domain,Crypto
  - RULE-SET,TEST / Domain,Test
  - RULE-SET,Block / Domain,Block
  - RULE-SET,Proxy / Domain,Global
  - RULE-SET,Globe / Domain,Global
  - RULE-SET,Direct / Domain,Mainland
  - RULE-SET,China / Domain,Mainland
  - RULE-SET,China / IP,Mainland,no-resolve
  - RULE-SET,Private / Domain,Mainland
  - MATCH,Others

# =======================================================================================
# è§„åˆ™é›†æä¾›è€…
# ç›®å‰ä½¿ç”¨https://gh-proxy.com/åŠ é€Ÿï¼Œå¯æ ¹æ®ç½‘ç»œæƒ…å†µï¼Œé€‰æ‹©ä»¥ä¸‹åŠ é€Ÿåœ°å€ï¼Œè‡ªè¡Œè°ƒæ•´ï¼š
# https://cdn.jsdelivr.net/ https://fastly.jsdelivr.net/ https://testingcf.jsdelivr.net/
# =======================================================================================
rule-anchor:
  ip: &ip {type: http, interval: 86400, behavior: ipcidr, format: mrs}
  domain: &domain {type: http, interval: 86400, behavior: domain, format: mrs}
  class: &class {type: http, interval: 86400, behavior: classical, format: text}

rule-providers:
  TEST / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Check.list"}
  ChatGPT / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/openai.mrs"}
  Claude / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Claude/Claude.list"}
  Meta AI / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/MetaAi.list"}
  Perplexity / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/perplexity.mrs"}
  AI / Domain: {<<: *class, url: "https://raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/AI.list"}
  Copilot / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Copilot.list"}
  Gemini / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Gemini.list"}
  GitHub / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/github.mrs"}
  Telegram / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/telegram.mrs"}  
  Telegram / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/telegram.mrs"}
  Twitter / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/x.mrs"}
  WhatsApp / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Whatsapp/Whatsapp.list"}
  Facebook / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/facebook.mrs"}
  Amazon / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/amazon.mrs"}
  Apple-CN / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple-cn.mrs"}
  Apple / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/apple.mrs"} 
  Microsoft / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/microsoft.mrs"}
  OKX / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/okx.mrs"}
  Bybit / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/bybit.mrs"}
  Binance / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/binance.mrs"}
  TikTok / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/tiktok.mrs"}
  Netflix / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/netflix.mrs"}
  Netflix / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/netflix.mrs"}
  Disney / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/disney.mrs"}
  HBO / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/hbo.mrs"}
  Spotify / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/spotify.mrs"}
  Steam / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/steam.mrs"}
  Epic / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Epic/Epic.list"}
  EA / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/EA/EA.list"}
  Blizzard / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Blizzard/Blizzard.list"}
  UBI / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/UBI/UBI.list"}
  PlayStation / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/PlayStation/PlayStation.list"}
  Nintend / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/Nintendo/Nintendo.list"}
  Proxy / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Proxy.list"}
  Globe / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Global/Global.list"} 
  Direct / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Direct.list"}
  China / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/cn.mrs"}
  China / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/cn.mrs"}
  Private / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/private.mrs"}
  Block / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Block.list"}
  Nvidia / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/blackmatrix7/ios_rule_script/refs/heads/master/rule/Clash/Nvidia/Nvidia.list"}
  Crunchyroll / Domain: {<<: *class, url: "https://gh-proxy.com/raw.githubusercontent.com/liandu2024/clash/refs/heads/main/list/Crunchyroll.list"}
  Reddit / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/reddit.mrs"}
  Youtube / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/youtube.mrs"}  
  Google / Domain: {<<: *domain, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geosite/google.mrs"}  
  Google / IP: {<<: *ip, url: "https://gh-proxy.com/github.com/metacubex/meta-rules-dat/raw/refs/heads/meta/geo/geoip/google.mrs"}
